<?
$PERM["lichnyy-kabinet-pokupatelya"]["2"]="D";
$PERM["lichnyy-kabinet-pokupatelya"]["3"]="D";
$PERM["lichnyy-kabinet-pokupatelya"]["4"]="D";
$PERM["lichnyy-kabinet-pokupatelya"]["7"]="X";
$PERM["lichnyy-kabinet-pokupatelya"]["8"]="D";
$PERM["lichnyy-kabinet-pokupatelya"]["5"]="D";
$PERM["lichnyy-kabinet-pokupatelya"]["6"]="D";
$PERM["lichnyy-kabinet-pokupatelya"]["*"]="D";
$PERM["lichnyy-kabinet-prodavtsa"]["*"]="D";
$PERM["lichnyy-kabinet-prodavtsa"]["8"]="X";
$PERM["search"]["6"]="W";
$PERM["products"]["6"]="W";
$PERM["services"]["6"]="W";
$PERM["news"]["6"]="W";
$PERM["contacts"]["6"]="W";
$PERM["company"]["6"]="W";
$PERM["index.php"]["6"]="W";
$PERM["/"]["*"]="R";
?>